[package]
name = "waytokserv"
version = "0.1.0"
authors = ["Javier Maldonado <3goliad@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
tokio-uds = "0.1"
