array_layout = "Block"
array_width = 40
chain_one_line_max = 40
chain_split_single_child = true
comment_width = 60
condense_wildcard_suffixes = true
error_on_line_overflow = false
fn_args_density = "Tall"
fn_args_layout = "Block"
fn_single_line = true
format_strings = true
match_block_trailing_comma = true
max_width = 80
space_after_bound_colon = false
space_after_type_annotation_colon = false
tab_spaces = 2
trailing_comma = "Always"
type_punctuation_density = "Compressed"
use_try_shorthand = true
where_density = "Tall"
where_style = "Rfc"
wrap_comments = true
